### ISSUE TITLE
InReplyToStatusId always null

### ISSUE THREAD

**Issue by rdahan156** [linvi/tweetinvi#178] opened 2016-03-30 09:52 UTC
Inside MatchingTweetReceived event handler, the InReplyToStatusId property is always null.

**Comment by linvi** [comment] 2016-03-30 09:54
I am pretty sure that this property is not available from Streams but I will verify.

**Comment by rdahan156** [comment] 2016-03-30 09:56
It worked for me in versions below 0.9.11.2

**Comment by linvi** [comment] 2016-03-30 09:58
Ok. good to know, I will verify this then.

Thanks :)

**Comment by linvi** [comment] 2016-03-30 10:05
Which specific version worked properly?
Can you confirm you are using `FilteredStream` in this case.

Thanks

**Comment by rdahan156** [comment] 2016-03-30 10:16
Yeah, i just checked the code, i am creating a filtered stream.

**Comment by rdahan156** [comment] 2016-03-30 13:53
Please fix this ASAP, my usage of this application depends on this property ;].

**Comment by linvi** [comment] 2016-03-30 15:00
I just tried during my lunch time and it is working for in 0.9.11.2 and 0.9.12.0.
I will continue investigate.

**Comment by rdahan156** [comment] 2016-03-30 15:01
Please try to debug this issue on my end and see what's going on.

**Comment by rdahan156** [comment] 2016-03-30 16:47
This is weird, all of the suddent it started working properly again, i bet this is Twitter's fault, not Tweetinvi.

Also, it seems like that a reply has to start with @<ScreenName> in order for this parameter to get filled.

https://twittercommunity.com/t/twitter-status-update-in-reply-to-status-id-is-null-always/18910

**Comment by rdahan156** [comment] 2016-03-30 17:51
The stream keeps firing TweetReceived handler with events that happened in the past, i think, please check into this.

**Comment by rdahan156** [comment] 2016-03-30 17:55
i'm going to use InReplyToScreenName as a temporary fix.

**Comment by linvi** [comment] 2016-03-30 20:32
> TweetReceived handler with events that happened in the past

This can happen if you do not handle the events quick enough or if the Twitter API is slow.

Concerning your skype message, please note that `retweet` and `reply` are 2 different concepts.
A tweet is *either* a `reply`, or a `retweet`. If a message is added to a retweet, this is no longer considered by Twitter as a retweet but as a `quoted tweet`.

**Comment by rdahan156** [comment] 2016-03-31 18:26
I want to say, that i just tested my client with 0.9.10.2 and it works normally fine, the TweetReceived handler doesn't get executed when someone writes a status that beginds with a @screenName (@username text) not to a status (tweet).

**Comment by linvi** [comment] 2016-04-01 16:38
So, do we agree that it is not a bug?
Can I close this?

**Comment by rdahan156** [comment] 2016-04-01 17:21
I'm still not sure if it's a bug, might be a glitch.

you should do a source code comparison with latest version against 9.10.2

**Comment by linvi** [comment] 2016-04-09 18:52
I am closing the issue as I don't think it is one :)

Keep reporting everything you don't consider being normal!

**Closed by linvi** 2016-04-09 18:52 UTC
Labels: bug
