### ISSUE TITLE
Tweetinvi.Core.Extensions TweetLength method returns wrong number

### ISSUE THREAD

**Issue by leventeolahx** [linvi/tweetinvi#488] opened 2017-04-13 21:22 UTC
Hello Linvi,

Just noticed a small (I think regex, in .Net) bug in the StringExtension class. When the tweet contains a link in format: "te-st.co" (without hyphen it works), TweetLength method doesn't count it as link. 

For me for the following string returned 132: "Lorem Ipsum is #simply dummy text of the printing and #typesetting industry. Lorem Ipsum has ☝😀

been the industry's standa te-st.co". However in twitter editor is 147 (as -7).

Regards,
Levente

**Comment by JoshKeegan** [comment] 2017-04-21 12:12
This is a duplicate of #468 
If it's causing you problems, as PR was submitted to fix it.
Cheers,
Josh

**Closed by JoshKeegan** 2017-04-21 12:12 UTC
Labels: bug
