### ISSUE TITLE
Potential Deadlock

### ISSUE THREAD

**Issue by anirudhsanthiar** [linvi/tweetinvi#99] opened 2016-01-04 12:23 UTC
The API for accessing the results of `Task` synchronously in the `SynchronousInvoker` should not be public. Blocking on the results of asynchronous methods can cause deadlocks: see, for example,
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

A GUI/MVC based client of Tweetinvi that uses this API can deadlock. A short example follows:
```
   // An example async method
   public async Task CopyFilesAsync(StreamReader Source, StreamWriter Destination)
   {
     char[] buffer = new char[0x1000];
     int numRead;
     while ((numRead = await Source.ReadAsync(buffer, 0, buffer.Length)) != 0)
     {
       await Destination.WriteAsync(buffer, 0, numRead);
     }
   }

   // code that deadlocks
   ISynchronousInvoker syncInvoker = new SynchronousInvoker();
   string UserDirectory = @"C:\testing\";

   using (StreamReader SourceReader = File.OpenText(UserDirectory + "set5draft"))
   {
      using (StreamWriter DestinationWriter = File.CreateText(UserDirectory + "CopiedFile.txt"))
      {
         syncInvoker.ExecuteSynchronously(CopyFilesAsync(SourceReader, DestinationWriter));
      }
   }
```

Also, all calls to `ExecuteSynchronously` within tweetinvi, such as `synchronousInvoker.ExecuteSynchronously(StartStreamAsync(url));` should either ensure that the awaits within the async argument to `ExecuteSynchronously` do not capture context, or else `ExecuteSynchronously` may be refactored to use `Task.Run`

**Comment by linvi** [comment] 2016-01-06 14:41
**The API for accessing the results of Task synchronously in the SynchronousInvoker should not be public. Blocking on the results of asynchronous methods can cause deadlocks: see, for example,**

In tweetinvi I have taken the decision to have most of the classes available publicly so that people can do whatever they want with them. Obviously when using a `SynchronousInvoker` I would expect a user to know how `async` works.

**Also, all calls to ExecuteSynchronously within tweetinvi, such as synchronousInvoker.ExecuteSynchronously(StartStreamAsync(url)); should either ensure that the awaits within the async argument to ExecuteSynchronously do not capture context, or else ExecuteSynchronously may be refactored to use Task.Run**

I am not sure what you mean by do not capture context. Could you please provide more details/explanation? Is there anything wrong with `ExecuteSynchronously`?

Thanks for the feedback!

**Comment by anirudhsanthiar** [comment] 2016-01-07 03:46
To explain, first assume you have the following code that defines functions `foo` and `barAsync`
```
foo()
{
   t = barAsync();
   t.Wait();
   ...
}

async Task barAsync()
{
  ...
  Task t = await SomeOperationAsync();
  // some other code
  return t;
}
```

When `foo` first calls `barAsync`, the part up to the first await is executed synchronously. Then, typically, `barAsync` will create a fresh, incomplete Task object `t` and return it to `foo`, and register the code after the await to be called back when `SomeOperationAsync` actually completes. 
After the call back runs and the return statement in `SomeOperationAsync` executes, `t` is marked complete.

Now, imagine that `barAsync` has returned an incomplete task to `foo`. Should `foo` choose to perform a blocking wait on this task, then `foo`'s thread is blocked. In the meanwhile, `SomeOperationAsync` will complete, and look to run its call back (the remainder of `barAsync`). The default behaviour of .NET is to post the continuation representing the remainder of `barAsync` back to the original thread's event queue - this is what I meant by "Capturing the context". The only thing that can unblock the blocked thread is this continuation (because it will complete the task t, signalling the Wait()) but the continuation can never run because the thread is blocked on the Wait() - deadlock!

.NET threads record a "context" as part of their local storage in `System.Threading.SynchronizationContext.Current`. You could think of this as an abstraction for a scheduler. The default behaviour of await statements is to post the corresponding continuation back to this context. To have the continuation run on a threadpool thread instead, we may say `await SomeOperationAsync().ConfigureAwait(false)`, provided the code after the await does not access any object with thread affinity. Since there are many threadpool threads, even if one of them is blocked, the continuation could always run on another (except in the pathological case where every threadpool thread is blocked too).

The reason `ExecuteSynchronously` is dangerous is that if I'm developing a GUI app, say a Windows Forms app, and I have the code that follows in a button click handler (you can try this), it will result in a deadlock. 

```
  var userStream = Tweetinvi.Stream.CreateUserStream();
  userStream.StartStream();
```
The scenario is very similar to what I outlined above.
`StartStream` calls `_synchronousInvoker.ExecuteSynchronously(StartStreamAsync())`, which in turn waits on the Task object returned by `StartStreamAsync`


I hope this clarifies things. 
Further reading: Please also refer the article I linked in the earlier post, along with this [article](http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx) that has more details/potential fixes. This [stackoverflow](http://stackoverflow.com/questions/12456115/understanding-context-in-c-sharp-5-async-await) post has more details about SynchronizationContext

**Comment by linvi** [comment] 2016-01-21 14:07
Hello there, I would be keen to understand your example but I might miss something here is the program I created to simulate what I understood from your example : 

// Console App
``` c#
using System;
using System.Threading.Tasks;

namespace TestConcurrency
{
    public class Program
    {
        private static bool RUN = true;

        static void Main(string[] args)
        {
            var p = new Program();
            p.Foo();

            Console.WriteLine("Program Done");
            Console.ReadKey();
        }

        public void Foo()
        {
            var t = barAsync();
            t.Wait();
            Console.WriteLine("Done Food");
        }

        private async Task barAsync()
        {
            await Task.Run(() =>
            {
                while (RUN)
                {
                    Task.Delay(2000).Wait();
                    Console.WriteLine("Waiting at " + DateTime.Now.ToLongTimeString());
                }
            });

            Console.WriteLine("Done BarAsync");
        }
    }
}
```

The program is behaving the way I would expect from it : 

``` 
Waiting at 2:07:03 PM
Waiting at 2:07:15 PM
Done BarAsync
Done Food
Program Done 
```

Am I missing something obvious here?

**Comment by linvi** [comment] 2016-01-21 15:27
Reading further in the article I think I do understand what you are referring to. The problem is that in my example I am not using the ThreadPool up to its limit. Would you agree?

**Comment by linvi** [comment] 2016-01-21 17:30
Hi there, so I am still reviewing my code after reading the article.
I would like to have your point of view on this, could we discuss about this on gitter (github chat system). I invited you already in a channel.

Thanks

**Comment by anirudhsanthiar** [comment] 2016-01-22 03:36
I've responded over at gitter...

**Comment by linvi** [comment] 2016-02-10 01:10
A very big thank you to @anirudhsanthiar who has been of a great help. I really appreciate the time you spent to help me improve the library.

I can now safely close this issue without any deadlock!

**Closed by linvi** 2016-02-10 01:10 UTC
Labels: bug

**Comment by linvi** [comment] 2016-02-10 02:17
Associated with https://github.com/linvi/tweetinvi/issues/124
