### ISSUE TITLE
Make stream match retweets

### ISSUE THREAD

**Issue by Niko-O** [linvi/tweetinvi#356] opened 2016-10-05 21:27 UTC
I would like to keep track of retweets of a tweet I publish, retweets of those retweets, retweets of those, and so on. I think the right way to do this is to tell a filtered stream to filter by retweets of a tweet. But how would I do that?
And how can I, possibly by using the same stream which finds retweets, find certain hashtags? Do I simply use `Stream.AddTrack("#MyHashtag")`?
The documentation does not seem to mention hashtags and retweets.

**Comment by linvi** [comment] 2016-10-05 23:26
Hello,

You can get all the tweets published by a user by using `AddFollow(userId)`. This also allow you to track the retweets of any tweet this user published.

You can find more about it here : https://dev.twitter.com/streaming/overview/request-parameters > Follow

### Follow Parameter
> A comma-separated list of user IDs, indicating the users whose Tweets should be delivered on the stream. Following protected users is not supported. For each user specified, the stream will contain:

> Tweets created by the user.
Tweets which are retweeted by the user.
Replies to any Tweet created by the user.
Retweets of any Tweet created by the user.
Manual replies, created without pressing a reply button (e.g. “@twitterapi I agree”).
The stream will not contain:

> Tweets mentioning the user (e.g. “Hello @twitterapi!”).
Manual Retweets created without pressing a Retweet button (e.g. “RT @twitterapi The API is great”).
Tweets by protected users.

If you want to track a hashtag, you are correct, you will only have to add a new `Track`.

**Comment by linvi** [comment] 2016-10-05 23:26
`// TODO : Create documentation for Track Hashtags + Retweets`

**Comment by Niko-O** [comment] 2016-10-06 00:28
If I understand right this will only track tweeets which are written by the specified user, which is not what I want. I did the following test:

- I have published a tweet and noted the ID.
- I then used the following code:

    Dim WithEvents Stream As Tweetinvi.Streaming.IFilteredStream
    Async Sub DoIt()
        Tweetinvi.ExceptionHandler.SwallowWebExceptions = False
        Tweetinvi.Auth.SetUserCredentials(...)
        Stream = Tweetinvi.Stream.CreateFilteredStream()
        Stream.FilterLevel = Tweetinvi.Streaming.Parameters.StreamFilterLevel.None
        Stream.StallWarnings = True
        Stream.AddFollow(Tweetinvi.Tweet.GetTweet(The ID of the original Tweet).CreatedBy, AddressOf TrackReceived)
        Await Stream.StartStreamMatchingAnyConditionAsync
    End Sub
    'EventHandler-Methods for all events of Stream plus TrackReceived, each logging the event.

- Somebody retweeted my tweet.
- The JsonObjectReceived-Event was raised. The containing JSON correcty referred to the retweet.
- The NonMatchingTweetReceived-Event was raised. The ID was the TweetId of the retweet.
So tweetinvi got the message but how do I tell it that it should not be filtered?
And what I did not test because I don't have enough people: How do I make sure that I also receive a message when somebody retweets the retweet?

**Comment by linvi** [comment] 2016-10-06 00:37
> The NonMatchingTweetReceived-Event was raised. The ID was the TweetId of the retweet.

This is currently the expected behaviour because the user who created the retweet is not a user that you are currently tracking.

> How do I make sure that I also receive a message when somebody retweets the retweet?

I am not sure the Twitter Stream API will return this information. You will have to test it.
I will be keen to know what it does.

**Comment by Niko-O** [comment] 2016-10-06 00:48
> This is currently the expected behaviour because the user who created the retweet is not a user that you are currently tracking.
Any ideas about how I could make it work? Possibly without parsing the JSON myself ;)
I can modify tweetinvi to match my needs, if it is required.

**Comment by linvi** [comment] 2016-10-06 00:51
`NonMatchingTweetReceived` contains the `Tweet`. Isn't it enough for what you want to do?

**Comment by linvi** [comment] 2016-10-06 00:53
``` c#
var fs = Stream.CreateFilteredStream();

fs.NonMatchingTweetReceived += (sender, args) =>
{
    var tweet = args.Tweet;
    var retweet = tweet.RetweetedTweet;

    if (retweet != null && retweet.CreatedBy.Id == 42)
    {
        // Do your logic here
    }
};
```

**Comment by linvi** [comment] 2016-10-06 00:55
I am done for tonight. I will answer any other question tomorrow (it is 2 am here!).

See you tomorrow.

**Comment by Niko-O** [comment] 2016-10-06 00:56
Oh, whoops. I only logged the ID and forgot that there is more data.
I am currently doing a test about the retweet of retweets. I will look at the tweet data in more detail and tell you what happens.

**Comment by Niko-O** [comment] 2016-10-06 02:20
Ok. The situation is as follows:
I use the code from above to track a tweet (tweet 1) of person 1.

1. Person 2 retweets tweet 1, creating tweet 2. This tweet is tracked by the stream as a "non matching tweet" (which is as expected).
2. Person 3 retweets tweet 2, creating tweet 3. This tweet is **not** tracked by the stream. The number of retweets on tweets 1 and 2 **do** however say "2". So twitter knows about tweet 3 but I don't receive the update.
3. Person 3 removes tweet 3.
4. Person 3 retweets tweet 2 again, creating tweet 4. This tweet suddenly **is** tracked by the stream (again, as a "non matching tweet").
5. Person 2 removes tweet 2 and person 3 removes tweet 4.
6. Person 2 retweets tweet 1 again, creating tweet 5. We are now back at step 1. The first retweet of tweet 5 won't be tracked, successive retweets will be.

I don't know whether that's a problem in Tweetinvi or a problem in Twitter, but it should not be this way.
Do you suggest to contact the Twitter support?

And it's also 3 am here, so good night ;)

**Comment by Niko-O** [comment] 2016-10-16 06:07
Hi. Just checking back to see whether you know anything new about this issue, since no new comments were added for quite a few days.

**Comment by linvi** [comment] 2016-10-16 22:18
Hello @Niko-O, I will get back to you tomorrow evening, I was on holiday but I am back now.

**Comment by linvi** [comment] 2016-10-18 01:09
> Ok. The situation is as follows:
> I use the code from above to track a tweet (tweet 1) of person 1.

> Person 2 retweets tweet 1, creating tweet 2. This tweet is tracked by the stream as a "non matching tweet" (which is as expected).
> Person 3 retweets tweet 2, creating tweet 3. This tweet is not tracked by the stream. The number of retweets on tweets 1 and 2 do however say "2" (on the Twitter website, see edit below). So twitter knows about tweet 3 but I don't receive the update.
> Person 3 removes tweet 3.
> Person 3 retweets tweet 2 again, creating tweet 4. This tweet suddenly is tracked by the stream (again, as a "non matching tweet").
> Person 2 removes tweet 2 and person 3 removes tweet 4.
> Person 2 retweets tweet 1 again, creating tweet 5. We are now back at step 1. The first retweet of tweet 5 won't be tracked, successive retweets will be.
I don't know whether that's a problem in Tweetinvi or a problem in Twitter, but it should not be this way.
Do you suggest to contact the Twitter support?

To make sure that the problem does not come from Tweetinvi but from Twitter verify that the event `stream.JsonObjectReceived` is not raised.

If it is not raised, the problem comes from Twitter. If it is raised, please let me know and I will do further investigation.

> Between steps 2 and 3:
> Tweetinvi.Tweet.GetTweet(ID of Tweet 1).GetRetweets returns 2 items, as expected
Tweetinvi.Tweet.GetTweet(ID of Tweet 2).GetRetweets returns 0 items but it should be 2 (to be consistent with what's shown on the Twitter website)!

Tweetinvi is returning the data that Twitter provides. But in this case I think it is correct. On Twitter, the number of retweets displayed is the number of retweets of the original tweet. But if you want to get the number of retweets from second tweet, I think there is some logic for returning 0.

> Between steps 3 and 4:
> Tweetinvi.Tweet.GetTweet(ID of Tweet 1).GetRetweets suddenly returns 0 items too. even though tweet 2 still exists!
Tweetinvi.Tweet.GetTweet(ID of Tweet 2).GetRetweets still returns 0 items.

I agree this does not makes sense.

> Between steps 4 and 5:
> Tweetinvi.Tweet.GetTweet(ID of Tweet 1).GetRetweets still returns 0 items.
Tweetinvi.Tweet.GetTweet(ID of Tweet 2).GetRetweets still returns 0 items.

Same here.

Please ask this type of question on https://twittercommunity.com. Share the post url on this issue so that I can keep track of it and update Tweetinvi if required.

**Comment by Niko-O** [comment] 2016-10-18 21:37
I tried it again and I can confirm that the JsonObjectReceived-Event is not raised.
See attached screenshot. The first received tweet is tweet 2. The second one is tweet 4. Tweet 3 never arrived.
![retweet of retweet](https://cloud.githubusercontent.com/assets/4943909/19496408/4cab4124-957f-11e6-84ad-0d940162a3e1.png)
In the screenshot you can alsosee all of the other windows which show events raised by the stream (and the TrackReceived-window which is the callback method passed to the stream's AddFollow-method). Only the StreamStart-, StreamResumed-, NonMatchingTweetReceived- and JsonObjectReceived-Events were raised.

Thank you for informing me about the liked website. I will ask there and post the link here, but before I do that:
The application I am using uses credentials which are linked to my Twitter account. So far I have tried this test with me being person 2 and me being person 3. But just now I have tried it with me being neither: Neither tweet 2 nor tweet 3 are tracked. I have no idea why this is happening.
Unfortunately I don't have enough people available for testing so I can't easily try different combinations.

**Comment by linvi** [comment] 2016-12-14 20:52
Hello, I have worked again on this issue and I think Twitter has changed how the tweets are matched.
I think most of the problems we were encountering have been fixed on their side.

Could you please take a look at it?

In the meantime I created a new work item for `QuotedTweets` which are currently matched by `FilteredStreams` but returned as part of `NonMatchingTweetReceived`.

**Comment by linvi** [comment] 2016-12-15 01:29
After working on the `QuotedTweet` matching for the `FilteredStream` I think this will solve your problem please take a look at it. #419.

Thanks for reporting this problem and I hope you will appreciate the new solution to solve this problem.

**Closed by linvi** 2016-12-15 01:29 UTC
Labels: documentation, question
