### ISSUE TITLE
TweetInvi does not work with ARM.

### ISSUE THREAD

**Issue by danielgraham** [linvi/tweetinvi#514] opened 2017-05-21 21:35 UTC
'DWP Display.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.1.1_1.1.24920.0_x86__8wekyb3d8bbwe\System.Private.CoreLib.ni.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\entrypoint\DWP Display.exe'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.1.1_1.1.24920.0_x86__8wekyb3d8bbwe\mscorlib.ni.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\WinMetadata\Windows.winmd'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.InteropServices.WindowsRuntime.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.WindowsRuntime.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.WindowsRuntime.UI.Xaml.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Collections.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Core.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Private.Uri.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Net.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Net.Requests.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Threading.Tasks.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Net.Http.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Newtonsoft.Json.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Diagnostics.Debug.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Autofac.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Controllers.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Credentials.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Factories.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Logic.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.WebLogic.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Streams.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Core.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Linq.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.Extensions.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Linq.Expressions.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Net.Http.Primitives.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Net.Primitives.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Reflection.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Threading.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Reflection.TypeExtensions.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Reflection.Emit.Lightweight.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Reflection.Emit.ILGeneration.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Reflection.Primitives.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.Serialization.Primitives.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Globalization.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Microsoft.Threading.Tasks.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Diagnostics.Tracing.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.IO.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.Serialization.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Text.Encoding.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Text.RegularExpressions.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\Tweetinvi.Security.dll'. Cannot find or open the PDB file.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Diagnostics.DiagnosticSource.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Runtime.InteropServices.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Dynamic.Runtime.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Reflection.Extensions.dll'. Module was built without symbols.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.ObjectModel.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Xml.XDocument.dll'. Symbols loaded.
'DWP Display.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\danie\Source\Repos\DWP Display\DWP Display\bin\x86\Debug\AppX\System.Xml.ReaderWriter.dll'. Symbols loaded.
The thread 0x407c has exited with code 0 (0x0).
The thread 0x880 has exited with code 0 (0x0).
The thread 0x2a90 has exited with code 0 (0x0).
The thread 0x394c has exited with code 0 (0x0).

![arm](https://cloud.githubusercontent.com/assets/6833852/26287538/baa56778-3e75-11e7-890e-40d3a326f916.PNG)
![coding](https://cloud.githubusercontent.com/assets/6833852/26287539/baa8a87a-3e75-11e7-9010-9e0fd728282f.PNG)
![x86](https://cloud.githubusercontent.com/assets/6833852/26287537/baa46df0-3e75-11e7-80ed-446fec71b84a.PNG)

**Comment by linvi** [comment] 2017-05-22 01:36
Thank you for all of this.
Does your code go to the `ArgumentException` or the `TwitterException`?

**Comment by danielgraham** [comment] 2017-05-23 20:28
I get neither exception. It's as if it works but returns nothing, no error at all

**Comment by amodoriccio** [comment] 2017-06-14 09:46
Same here, is there a temporary solution ?

**Comment by linvi** [comment] 2017-06-14 10:10
Could you share your project please.

**Comment by amodoriccio** [comment] 2017-06-14 12:46
`Imports Windows.ApplicationModel.Background
Imports Tweetinvi

Public NotInheritable Class StartupTask
    Implements IBackgroundTask
    Private _deferral As BackgroundTaskDeferral

    Public Sub Run(taskInstance As IBackgroundTaskInstance) Implements IBackgroundTask.Run
        _deferral = taskInstance.GetDeferral()

        Auth.SetUserCredentials("XXXXXXXXX", "XXXXXXXXX", "XXXXXXXXX-XXXXXXXXX", "XXXXXXXXX")
        StreamCommand()
    End Sub

    Async Sub StreamCommand()
        Dim _userstream = Stream.CreateUserStream()

        AddHandler _userstream.StreamIsReady, Sub(sender, args)
                                                  Debug.WriteLine("Stream Ready")
                                              End Sub
        Await _userstream.StartStreamAsync
    End Sub
End Class`

This basic thing does nothing on ARM. But works on other plateforms.

**Comment by linvi** [comment] 2017-06-18 21:02
Hello there, could you please check Tweetinvi version 2.0 and let me know if you still encounter this problem.

Thanks

**Comment by amodoriccio** [comment] 2017-06-19 06:02
Still not working for me.

A simple code (like this one) does nothing and Auth return nothing too : 

```vbnet
Public NotInheritable Class StartupTask
    Implements IBackgroundTask
    Private _deferral As BackgroundTaskDeferral

    Public Sub Run(taskInstance As IBackgroundTaskInstance) Implements IBackgroundTask.Run
        _deferral = taskInstance.GetDeferral()

        Auth.SetUserCredentials("XXXXXXXXX", "XXXXXXXXX", "XXXXXXXXX-XXXXXXXXX", "XXXXXXXXX")
        StreamCommand()
    End Sub

    Sub StreamCommand()
        Dim _userstream = Stream.CreateUserStream()

        AddHandler _userstream.StreamIsReady, Sub(sender, args)
                                                  Debug.WriteLine("Stream Ready")
                                              End Sub

        AddHandler _userstream.StreamStarted, Sub(sender, args)
                                                  Debug.WriteLine("Stream Start")
                                              End Sub

        _userstream.StartStream()
    End Sub
End Class
```

**Comment by linvi** [comment] 2017-10-08 18:58
Hello @danielgraham, @amodoriccio 

I finally have time to look into this issue. I guess you probably moved to another topic.
Regardless, could you please let me know which type of hardware you are trying to create the project for.

I tested the project for Android ARM and it worked as expected.
Could you please provide more information regarding your project.
- Target Hardware
- Version of .NET....

Actually if you could share a sample project where I could reproduce the issue it would be ideal.
I have already attempted for a while to not make it work without any success.

Thanks,
Linvi

**Comment by linvi** [comment] 2017-10-21 18:13
I have also tested the project on Raspberry Pi 3.

Feel free to reopen if you still encounter the problem.

**Comment by amodoriccio** [comment] 2017-11-14 18:14
Sorry, but still have the problem.

- Target hardware : Raspberry Pi 3 with W10 IOT (v.10.0.16299.19)
- .net Framework 4.7

I can't get AuthenticatedUser or create UserStream, but I can tweet. Authentification seems to be partially functional.

Thank you in advance for your answer and thank you again for your hard work. 👍

**Comment by linvi** [comment] 2017-11-15 08:14
Did you try the project : https://github.com/linvi/tweetinvi/tree/master/Examplinvi.UAP

I have not tested `UserStream` on it but `FilteredStream` is working fine.

**Comment by amodoriccio** [comment] 2017-11-15 09:58
Yes, I tried this project. I have exactly the same problem. Authentification seems working. But can't `GetAuthenticatedUser`, can't use `UserStream`. But tweeting, `FilterStream` etc... working great.

![devenv_2017-11-15_10-55-37](https://user-images.githubusercontent.com/29174698/32829915-d230a6a0-c9f3-11e7-9a53-d78adae8f066.png)

**Comment by linvi** [comment] 2018-03-24 20:20
Hello,

I have tried this again and still unable to reproduce. Did you make any progress on your project or did you give up?

You mentioned that Tweeting seems to work with the same credentials.
As a result this does not look like a problem that would be only dependent on the architecture.

Therefore could you disable the `ExceptionHandler.SwallowException` and let me know what exception you are receiving when you execurting the `var user = User.GetAuthenticatedUser()`.

Thanks,
Linvi

**Comment by amodoriccio** [comment] 2018-03-24 20:56
Hey !

I just tested my old project and ... I don't know why but ... it works great (!!!). I tried so many times. I guess the problem came directly from Twitter API. Anyway, thank you for your work. I use Tweetinvi regularly with a .Net Core 2.0 project. As soon as I can afford it, I won't hesitate to give you some tip, you deserve it. Thanks again! I look forward to testing the next version. 👍🙂

**Comment by linvi** [comment] 2018-03-24 23:55
Hello,

Thank you for the feedback. I am therefore closing the issue.
I will try to release 2.2 by tomorrow. I will be glad to have feedback.

Thanks for reporting the issue and constantly being prompt to reply.

Have a great weekend.
Linvi

**Closed by linvi** 2018-03-24 23:55 UTC
Labels: bug
