### ISSUE TITLE
Tweetinvi stopped working.

### ISSUE THREAD

**Issue by DavidBusayo** [linvi/tweetinvi#866] opened 2019-05-26 11:14 UTC
i am using tweetinvi from last several month. now i am facing error "reference null" in same code which is running fine last week. 
i am using TweetInvi 4.0 right now.
any help regarding this will be highly appreciated!
Regards

**Comment by GodsWithin** [comment] 2019-05-26 11:28
Duplicate of #850

**Comment by DavidBusayo** [comment] 2019-05-26 16:03
can you upload modified DLL which is working?

**Comment by DavidBusayo** [comment] 2019-05-26 16:43
@GodsWithin i have modified the dll can you explain step by step how to replace DLL in the project. because i am still facing errors

**Comment by GodsWithin** [comment] 2019-05-27 08:03
Just replace the one you're using with the modified one in the references of your project.

**Comment by DavidBusayo** [comment] 2019-05-27 09:13
@GodsWithin ok thanks

**Comment by linvi** [comment] 2019-05-27 20:45
Please follow #850 .

**Closed by linvi** 2019-05-27 20:45 UTC
Labels: bug, duplicate
