### ISSUE TITLE
The type initializer for 'Tweetinvi.Auth' threw an exception. System.Collections

### ISSUE THREAD

**Issue by KoalaBear84** [linvi/tweetinvi#871] opened 2019-05-29 06:25 UTC
I've seen similar issues in this repository, but couldn't fix it. If I revert back the Tweetinvi 4.0 it works.

There are 2 inner exceptions.

First (this version does not exist on Nuget):
FileNotFoundException: Could not load file or assembly 'System.Collections, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Second:
FileNotFoundException: Could not load file or assembly 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I've also tried something this for app.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
  <runtime>
    <assemblyBinding>
      <dependentAssembly>
        <assemblyIdentity name="System.Collections" publicKeyToken="B03F5F7F11D50A3A" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by paranoiks** [comment] 2019-05-29 09:17
I have the exact same issue since updating to Tweetinvi to latest

**Comment by semuer** [comment] 2019-05-31 00:54
Same issue after 4.0.1. Resolved by compiling Tweetinvi library from source code.

**Comment by KoalaBear84** [comment] 2019-06-18 08:21
Any news? 😇

**Comment by WhiteLionATX** [comment] 2019-06-18 20:38
Same here. Any solutions ?

**Comment by ajntcode** [comment] 2019-06-23 10:52
Same issue using 4.0.1 from NuGet.

**Comment by paranoiks** [comment] 2019-06-24 08:04
I managed to solve it. In the end, I had to get the latest version of the code and make sure all the projects in the solution have ".Net Standard 2.0" set as their Target Framework. After that rebuild and manually reference the new DLLs in your project

**Comment by lazmond3** [comment] 2019-06-27 01:28
You should specify .NET Framework 4.6.x version not  4.7.2 when making a project.

**Comment by KoalaBear84** [comment] 2019-06-27 09:01
Isn't that more like a workaround?

**Comment by linvi** [comment] 2019-07-14 17:57
It seems like a workaround. Sorry for not looking at this earlier.

I will be ensuring that next version does work for them all.

**Comment by linvi** [comment] 2019-07-14 19:27
It seems to be a problem with referencing .NETStandard libraries to .NET Framework 4.7.1 and 4.7.2

* https://github.com/dotnet/standard/issues/567
* https://github.com/IdentityModel/IdentityModel/issues/70

I did not find alternatives for now.

**Comment by linvi** [comment] 2019-07-14 19:49
I have tested and it seems that .NET Framework 4.8 have fixed the issue.

**Comment by WhiteLionATX** [comment] 2019-07-14 21:36
4.8 fixed SetUserCredentials problem for me. GetAuthenticatedUser throws still null with 4.8

**Comment by linvi** [comment] 2019-07-14 23:27
Did you try to delete your bin/obj folders?

If yes and it still does not work.

* Could you let me know if the project you tried on was new / upgraded?
* Can you share your `App.Config` and `.csproj`?
* Can you tell me what type of project you are trying to create? (console, aspnet, desktop, library)

* Finally can you please try and let me know if you have the same problem for a new project?

**Comment by d668** [comment] 2019-07-31 04:59
So you basically don't support anything less that 4.8 that was released just few months ago on 18 April 2019... Nice

**Comment by linvi** [comment] 2019-08-24 12:26
> So you basically don't support anything less that 4.8 that was released just few months ago on 18 April 2019... Nice

d668, your comment is a bit misplaced. I have spent years of work continuously updating, fixing, helping the community. At the moment I have very little amount of time to dedicate on the project.

Instead of criticizing wouldn't your time be better spent helping and trying to find a solution to the problem?

**Comment by yasha107** [comment] 2019-08-26 12:41
.NET Framework 4.8 have not fixed the issue for me, still having the error

**Comment by linvi** [comment] 2019-08-26 22:12
I have updated the version of Tweetinvi to 4.0.2 so that it becomes compatible with .NET Framework 4.7.2.

Please note that the it came with a cost which is the fact that for the moment Tweetinvi is no longer a StrongName package.

I will be glad to hear feedback on the subject before I close the issue.

**Comment by petevick** [comment] 2019-10-03 15:59
Downloaded the latest version - still getting the error on Android in the release version (debug is fine). Tried recompiling locally as suggested, and replacing the DLL's but to no avail :(
Any ideas please?

**Comment by linvi** [comment] 2019-10-04 00:10
Thanks for reporting. No idea on top of my head but will try to prioritise this and give you some feedback.

**Comment by petevick** [comment] 2019-10-04 08:18
Great – Thanks.

Works perfectly in iOS/UWP and Android(debug) mode. Just Android Release that causes the problem.

Thanks

Pete

**Comment by linvi** [comment] 2020-03-05 00:03
5.0 has been tested with debug + release on Android x86.
Will provide more feedback before release of 5.0.

**Comment by petevick** [comment] 2020-03-05 08:24
Great - Thanks. Looking forward to it.

**Comment by linvi** [comment] 2020-03-05 13:23
@petevick 

Do you think you could provide me with a very minimalistic project and set of compilation instructions to reproduce the current issue so that I can absolutely confirm that the issue will not happen anymore.

Thanks,
Linvi

**Closed** 2020-03-29 19:09 UTC
Labels: bug
