### ISSUE TITLE
GetUserFromID Rate Limit application / consumer wide?

### ISSUE THREAD

**Issue by komBAS** [linvi/tweetinvi#93] opened 2015-12-07 14:15 UTC
Hi linvi,

I use the following code within my background worker tasks and in my windows forms app you can have several of theses tasks to simultaneously get and store the follower details of own twitter accounts in a local database.

```
private void accounttask_DoWork(object sender, DoWorkEventArgs e)
{
 Auth.ExecuteOperationWithCredentials(creds, () =>
 {
                RateLimit.RateLimitTrackerOption = RateLimitTrackerOptions.TrackOnly;

                TweetinviEvents.QueryBeforeExecute += (senderT, args) =>
                {
                         ...
                }
});
ActualStep = 1;
GetFollowers();
ActualStep = 2;
GetFollowerDetails();
}




private void GetFollowerDetails()
{
Auth.ExecuteOperationWithCredentials(creds, () =>
{   
   for (int ix = 0; ix <= newFollowersID.Count - 1; ix++ )
   {
       long iUser = Convert.ToInt64(newFollowersID[ix]);

       var user = User.GetUserFromId(iUser);
       ...
   }
}
}
```

As I saw now, that even with different Twitter account credentials the Rate Limit of 181 for getting a user's details seems to be application wide (or consumer key wide).

Immediately if one of these tasks runs into the Rate Limit all other tasks of this kind go into idle mode and wait the Rate Limit to be resetted.

I am using 0.9.10.0

**Comment by komBAS** [comment] 2015-12-22 01:39
I need to push this because I still need a solution or, if my initial question is not clear enough, please let me know.
From the behaviour in my application it SEEMS that
<code>
Auth.ExecuteOperationWithCredentials
</code>
operates not per thread but application wide. Is that true?

Thanks!

**Comment by linvi** [comment] 2015-12-22 21:47
Hi, this behavior is not the intended one. Using `Auth.ExecuteOperationWithCredentials` should force the usage of the credentials that you specify. 

In your code though I cannot see what creds is. Whether it is a user creds or whether it is the application creds.

**Comment by komBAS** [comment] 2015-12-24 04:46
Oh, creds are the following twitter credentials
```
TwitterCredentials creds;
...
creds = new TwitterCredentials("xxx", "yyy", myAccount.AccessToken, myAccount.AccessTokenSecret);
```
Where xxx and yyy are the CONSUMER_KEY and the CONSUMER_SECRET.

MyAccount.AccessToken and myAccount.AccessTokenSecret are individual per task (background worker).

During debugging I see that each task has it's own credentials and that's the reason why I am confused because if one task gets into the rate limit, all other tasks (with individual credentials) fall into the rate limit too.

**Comment by linvi** [comment] 2016-01-06 15:40
Sorry for the late reply.

**During debugging I see that each task has it's own credentials and that's the reason why I am confused because if one task gets into the rate limit, all other tasks (with individual credentials) fall into the rate limit too**

I cannot test this right now but I will have a look. Are you saying that the reference to the `cred` instance is different? I am a bit confused as to what you are trying to point out.

**Comment by linvi** [comment] 2016-02-05 02:47
I have tried to reproduce your issue in a `BackgroundWorker` a `new Thread` as well as in a `Task` but I could not reproduce your problem.

If you are still interested by this issue let me know and we could have a private conversation over skype. If not I will close this issue in 3 days.

**Comment by komBAS** [comment] 2016-02-05 08:29
Hi linvi,

I have been very busy during the last weeks and yes, the problem is still an issue on my side.

I would appreciate a private conversation where I can send you some code examples to have a look at. Where can I send this to please?

**Comment by linvi** [comment] 2016-02-05 08:48
I have invited you on a private chat on [gitter.im](https://gitter.im/linvi/bug93).

Thanks

**Comment by linvi** [comment] 2016-02-09 01:09
Hello there, I have invited you on gitter but I am still waiting for you to reply.

**Comment by linvi** [comment] 2016-02-12 13:31
Closing the issue for the moment as I did not received any answer.

**Comment by komBAS** [comment] 2016-02-12 13:38
Hi linvi,

I tried to use your private chat this week but I only a received an

Gitter
404. This is not the chat you're looking for. Sorry.

The issue is still open for me, but as I said, I have plenty of work to do on my full time job and hadn't had a chance to work on this problem.

**Comment by linvi** [comment] 2016-02-12 14:24
Please simply login to https://gitter.im with your github account.
After that you will be able to access the chat.

**Comment by linvi** [comment] 2016-03-04 12:50
Problem was in the handling of TweetinviEvents that was made per thread instead of application wide.

New issue created to support this scenario : https://github.com/linvi/tweetinvi/issues/93

**Closed by linvi** 2016-03-04 12:50 UTC
Labels: bug
