### ISSUE TITLE
IObjectEntities in IMessage does not have Media object.

### ISSUE THREAD

**Issue by svncsvr** [linvi/tweetinvi#671] opened 2018-03-17 20:06 UTC
I need to get inbox messages with the media information.When I inspected twitter api response via Fiddler I noticed that response contains an object called media which contains original media source url.But tweetinvi IMessage objects seems to be not deserializing media field.
How can I access original media url in inbox or sentbox messages?

**Comment by philjt** [comment] 2018-03-17 21:04
I logged this as issue #624, and that has been fixed in the next version (2.2), not sure when it is due to be released though.

**Comment by linvi** [comment] 2018-03-18 03:34
Hello, the version 2.2 is due this week next weekend :)

I am closing this one as it is a duplicate of #624.

**Closed by linvi** 2018-03-18 03:34 UTC
Labels: enhancement
