### ISSUE TITLE
Can't publish tweet if message contains ! :  ( ) * symbols

### ISSUE THREAD

**Issue by McKlavishnikov** [linvi/tweetinvi#120] opened 2016-01-31 21:10 UTC
Can't publish tweet if message contains 
!
:
(
)
*
symbols 
However, there are no any problems with these symbols: <>{}[]№%?-_=+@#$%^&.,"';

Using TweetinviAPI -Version 0.9.10.2-W10-UAP -Pre

**Comment by linvi** [comment] 2016-02-01 13:56
I have been able to publish tweets containing all these characters.
Would you please let me know which type of project you are running it from (Xamarin iOS, Android, Windows Phone, Windows...)

Thanks

**Comment by McKlavishnikov** [comment] 2016-02-01 19:40
My project is type of 'Universal Windows Platform' (UWP) (for Windows 10 platform (both desktop and Phone))

**Comment by linvi** [comment] 2016-02-12 13:28
Could you please send me the error details as I have successfully published a tweet containing ALL of the characters you provided in a W10 app (tested on desktop and phone).

You can get the error details with the `ExceptionHandler`. 

``` c#
ExceptionHandler.WebExceptionReceived += (o, args) =>
{
    Message.Text += args.Value.WebException;
};
```

**Comment by McKlavishnikov** [comment] 2016-02-15 19:17
So, here is one new interesting detail about this error. 

This error occurs only if there are both Cyrillic letters and these special symbols ( ! : ( ) * ). So, I can post without any problems a message like "Hello!" (in English with '!'), I can post "Привет" (Russian 'hello' without '!'), but I can't post "Привет!" (Russian 'hello' with '!').

WebException	in ExceptionHandler is null. But I tried to collect some additional data in error args that can be useful:

Status
UnknownError

TwitterDescription
"Unauthorized -  Authentication credentials were missing or incorrect."

TwitterExceptionInfos
Code:	32
Label:	null
Message:	"Could not authenticate you."

Message
https://api.twitter.com/1.1/statuses/update.json?status=%D0%94%D0%BE%D0%B1%D1%80%D0%B5%21%20 web request failed.

**Comment by linvi** [comment] 2016-02-15 19:40
Thanks I will perform further investigation on this issue.

**Comment by linvi** [comment] 2016-02-29 10:21
Hello there, I have just tried to reproduce the issue with the latest version of Tweetinvi and I cannot reproduce it with `"Привет!"` and `"Привет!( ! : ( ) * )"`.

Could you please try the DLL that have been uploaded here : https://github.com/linvi/tweetinvi/releases/tag/0.9.11.0-alpha

**Comment by linvi** [comment] 2016-03-02 00:50
I am closing the issue for now. If you still encounter the problem please reopen it!

**Comment by McKlavishnikov** [comment] 2016-03-02 21:17
Hello. Sorry for not replying for some time.

Unfortunately, I can't test posting special symbols with this version of TweetInvi, because I can't authorize my app: 
1) I create TwitterCredentials:
TwitterCredentials appCredentials = new TwitterCredentials(ConsumerKey, ConsumerSecret, AccessToken, AccessTokenSecret);
2) string url = CredentialsCreator.GetAuthorizationURL(appCredentials);
3) -> Exception

I had the same problem with current standart 0.9.10.2 version, but in 0.9.10.2 W10-UAP version the same code works fine (let me remind, I'm developing a Windows 10 UWP app).

**Comment by linvi** [comment] 2016-03-02 22:05
Yes I know about this problem. 

Please use the following dll : https://github.com/linvi/tweetinvi/releases/download/0.9.11.0-alpha/Tweetinvi.0.9.11.0.-.alpha.zip

**Comment by McKlavishnikov** [comment] 2016-03-02 22:38
Thank you, now I can authorize my app, but unfortunately the problem's remained: I can post an English text with any symbols, but I can't post a Cyrillic text with those symbols :( 
Very weird problem...

**Comment by McKlavishnikov** [comment] 2016-03-02 23:02
A little update.
I assumed that problem may be in different system regional settings, so I change my system location to USA, units and etc. to English (USA), rebooted, rebuild, compile but problem hasn't changed.

And a little off-top. 
Previously I asked my friend to test the same issue with posting on the compiled version of my program (with 0.9.10.2 W10-UAP TweetInvi) and he couldn't, he failed on CredentialsCreator.GetAuthorizationURL(appCredentials), the error was: 
TypeInitialization_Type_NoTypeAvailable
TypeLoad_TypeNotFound, Tweetinvi.Core.Events.EventArguments.QueryAwaitingEventArgs, Tweetinvi.Core, Version=0.9.10.2, Culture=neutral, PublicToken=XXXXXXXX. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
(he ran the program on Windows 10). 
I know it's another bug and another thread should be opened, but I thought maybe this might help.

**Comment by linvi** [comment] 2016-03-03 02:17
> CredentialsCreator.GetAuthorizationURL(appCredentials), the error was: 
TypeInitialization_Type_NoTypeAvailable
TypeLoad_TypeNotFound, Tweetinvi.Core.Events.EventArguments.QueryAwaitingEventArgs, Tweetinvi.Core, Version=0.9.10.2, Culture=neutral, PublicToken=XXXXXXXX

This error is happening with the non UAP version of Tweetinvi. I have never experienced this issue with the 0.9.10.2 W10-UAP.

Could you please verify that he indeed used the right version.

As per the bug, would you be able to share your project?
I have tried various combination but unfortunately I could not reproduce it.

Thanks

**Comment by linvi** [comment] 2016-03-03 02:17
If you need your project to be private, you can share it via gitter : gitter.im/linvi.

**Comment by McKlavishnikov** [comment] 2016-03-03 20:20
Thank you for reply. 
About my friend's error – yes, maybe I gave him a wrong version, that's why I haven't created a new bug reported because this problem should be investigated by me firstly.

About the main problem with symbols. I separated Twitter Posting method from my project and uploaded it here:
https://drive.google.com/file/d/0B91Wd2TAZ4geNUhLNllzNjVjM0U/view?usp=sharing
The proble remained. I used 0.9.10.2-W10-UAP -Pre version (installed from Package Manager Console). 
If you want, you can contact me via email (file 'myemail.txt' in archive contains my email).

**Comment by linvi** [comment] 2016-03-03 21:30
I can reproduce the problem with your project.
I will investigate.

**Comment by linvi** [comment] 2016-03-03 21:49
First of all I have identified that the problem is happening only with Windows Universal App.

I'll get back to you with more info.

**Comment by linvi** [comment] 2016-03-04 01:26
**Fixed!!!!**

For some reason the HttpClientHandler was not sending the data the same way in "classical application" compared to "universal application". The Uri.EscapeDataString seems to have some inconsistency based on the platform it is running on. I have changed it to use EscapeUriString that works the same way on all the platforms.

The alpha libraries have been updated and are accessible here : https://github.com/linvi/tweetinvi/releases/tag/0.9.11.0-alpha.

**Comment by linvi** [comment] 2016-03-04 17:14
Let me know if it worked!

**Comment by trifroggy** [comment] 2016-03-11 09:56
Keeping on this thread since it seems related; feel free to move it if needed.  And my apologies if I missed a piece of info on some of the other documentation.

We have a user in France who tried to publish this:
Echanges #smartcity très intéressants pendant SmartCity Lyon: Métropole intelligente 2016

We logged:  BAD| 401 - Could not authenticate you. - Unauthorized -  Authentication credentials were missing or incorrect.

We are on 0.9.11 (from NuGet) in a classical app mode.  
This only happens when there is a # tag in there.  The same message without it goes through fine (we just tested it).
Any recommendations to get around this? (can't ask the French to stop using hashtags though :)  )

Let me know how we can help,
Thank you!

**Comment by McKlavishnikov** [comment] 2016-03-11 18:57
**linvi**
Sorry for not replying immediately. I installed 0.9.11 version from NuGet and everything works for me!!! Great!!! Thank you!!!

**trifroggy** 
I tested your message in my app (on last NuGet 0.9.11 release) and it's the same behavior for me as you described: can't post your full message, but can post without '#'.

**Comment by linvi** [comment] 2016-03-12 11:24
@trifroggy

I will work on a fix ASAP.

**Comment by linvi** [comment] 2016-03-15 00:51
I have reverted my changes temporarily. I am soooo busy that it is quite hard for me to allocated any time for this. But I will fix it as part of the next minor release.

Sorry for the delay.

**Comment by linvi** [comment] 2016-03-16 01:00
I have been able to track down the issue as being a bug with the `HttpClient`. I have opened a question on [StackOverflow](http://stackoverflow.com/questions/36025004/httpclient-does-not-send-same-request-in-w10-uap). And I will probably open a bug on the Microsoft website.

Tomorrow I will try to find an alternative to the problem.

**Comment by linvi** [comment] 2016-03-16 01:11
Created a bug on Microsoft github CoreFx project : https://github.com/dotnet/corefx/issues/6946

**Comment by linvi** [comment] 2016-03-20 00:25
The real problem comes from Microsoft `System.Net.Http.HttpClient` library. I have open a bug and it is planned to be solved in the next release of their library.

In the meantime, I have just issued a fix for the problem.

**Closed by linvi** 2016-03-20 00:25 UTC
Labels: bug
