### ISSUE TITLE
Multiple Upload.UploadImage

### ISSUE THREAD

**Issue by yangar** [linvi/tweetinvi#24] opened 2015-09-18 07:09 UTC
I m using the latest build from Nuget :0.9.9.6.
It's maybe a problem with the Credentials process. It was working with versions before Tweetinvi 0.9.9.x
The first tweet is well posted but i ve got an error and the second one :
Object reference not set to an instance of an object on : 
 var media = Upload.UploadImage(imageBytes);

``` c#
public class TwitterList
{
    public double longitude { get; set; }
    public double latitude { get; set; }
    public string Message { get; set; }
}
public async Task PostAlert(double longitude, double latitude, string Message)
{
    List<TwitterList> AlertList = new List<TwitterList>();
    AlertList.Add(new TwitterList { latitude = 37.386052, longitude = -122.083851, Message = "Test message 1 : " + DateTime.Now });
    AlertList.Add(new TwitterList { latitude = 42.386052, longitude = -122.083851, Message = "Test message 1 : " + DateTime.Now });

    foreach (var item in AlertList)
    {
        await PostTwitterAlert(item.longitude, item.latitude, item.Message);
        Response.Write(item.Message + "<br/>");
    }
}
public async Task PostTwitterAlert(double longitude, double latitude, string Message)
{
    try
    {
        var webClient = new WebClient();
        string GoogleUrl = "http://maps.google.com/maps/api/staticmap?center=" + latitude.ToString() + "," + longitude.ToString() + "&zoom=7&markers=label:E|" + latitude.ToString() + "," + longitude.ToString() + "&size=500x400&sensor=true";
        byte[] imageBytes = webClient.DownloadData(new Uri(GoogleUrl));
        var credentials = new TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

        var media = Upload.UploadImage(imageBytes);

        Coordinates Coordinates = new Coordinates(longitude, latitude);
        var tweet2 = Auth.ExecuteOperationWithCredentials(credentials, () =>
        {
            return Tweet.PublishTweet(Message, new PublishTweetOptionalParameters
            {
                Coordinates = Coordinates,
                Medias = new List<IMedia> { media }

            });
        });
    }
    catch (WebException e)
    {
        var exceptionStatusCode = Tweetinvi.ExceptionHandler.GetLastException().StatusCode;
        var exceptionDescription = Tweetinvi.ExceptionHandler.GetLastException().TwitterDescription;
        var exceptionDetails = Tweetinvi.ExceptionHandler.GetLastException().TwitterExceptionInfos.First().Message;
        Response.Write(exceptionDetails);
    }
}
```

**Comment by linvi** [comment] 2015-09-18 10:47
I will investigate this issue as soon as I can. I already have quite some work to do. I will get back to you.

**Comment by linvi** [comment] 2015-09-22 13:09
Hello,

Are you still experiencing the issue, I ask the question as it has been 4 days now and I would like to know whether this still needs to be investigated.

If yes, could you please provide a full stack trace of the issue.

Cheers,
Linvi

**Comment by yangar** [comment] 2015-09-22 14:33
[NullReferenceException: Object reference not set to an instance of an object.]
   Tweetinvi.Upload.UploadImage(Byte[] binary) +59
   earthquakes.zone.Controllers.<PostTwitterAlert>d__7.MoveNext() in D:\Fichiers_Pro\Controllers\TempController.cs:241
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   earthquakes.zone.Controllers.<PostAlert>d__6.MoveNext() in D:\Fichiers_Pro\Controllers\TempController.cs:224
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   System.Threading.Tasks.TaskHelpersExtensions.ThrowIfFaulted(Task task) +61
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +114
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +66
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +47
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +136
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +102
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +49
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +117
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +323
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +44
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +47
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +136
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +102
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +50
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +72
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +133
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +56
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +40
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +34
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +133
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +56
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +37
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +44
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +39
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +62
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +133
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +56
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +37
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +39
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +39
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +133
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +56
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +37
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +40
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9723757
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by yangar** [comment] 2015-09-22 14:36
Hello,

I also try to add a Thread.Sleep(5000); just after the download image process but i still get the exception.

Thank you,
Yann

**Comment by linvi** [comment] 2015-09-22 14:47
Thanks, I will investigate this issue tonight.

Please check github as I might need some more details.

Cheers,
Linvi

**Comment by linvi** [comment] 2015-09-23 00:18
Hi,

Could you please move the following line : `var media = Upload.UploadImage(imageBytes);` into the ExecuteOperationWithCredentials.

``` c#
Coordinates Coordinates = new Coordinates(longitude, latitude);
var tweet2 = Auth.ExecuteOperationWithCredentials(credentials, () =>
{
    var media = Upload.UploadImage(imageBytes);
    return Tweet.PublishTweet(Message, new PublishTweetOptionalParameters
    {
        Coordinates = Coordinates,
        Medias = new List<IMedia> { media }

    });
});
```

Let me know if this solves the issue.

**Comment by yangar** [comment] 2015-09-23 03:29
Hello linvi,
I still have the issue after moving `var media = Upload.UploadImage(imageBytes);` into the `ExecuteOperationWithCredentials`.
Does the process to send tweets in a loop with images working for you ?
To be exact it's working sometime for more than 1 image in the loop but when i got the `Object reference not set to an instance of an object`. i have to restart the pool to make it working again.

**Comment by linvi** [comment] 2015-09-23 08:22
Hi,

Thank you for the feedback. I am going to try with IIS as you seem to be working with it.
Can you please confirm that you are working on a Website stored on IIS as opposed to IIS Express?

I am going to try reproducing it with an MVC application stored in IIS, but in the meantime, would you be able to try using the Source Code of version 0.9.10.0 available on Github. You can do this by adding the Tweetinvi library projects  (all the projects starting with Tweetinvi) into your solution.

By doing so, I should be able to get more information out of the StackTrace and you'll probably be able to know where the Exception is thrown.

**Comment by linvi** [comment] 2015-09-23 14:50
Hi,

This is a quick message to let you know that I have finally been able to reproduce your issue and that I know how this issue will be fixed.

I will let you know when this is done.

Cheers,
Linvi

**Comment by Bastaspast** [comment] 2015-09-23 14:50
Hi,

Thanks for investigating this. Been using Tweetinvi since 2 days now and I am experiencing the same problem with images. I tried with uploadbinary, uploadimage, chunkeduploader, etc... After a while it's start spitting out these exceptions:

ExceptionMessage	ExceptionStackTrace
Object reference not set to an instance of an object at Tweetinvi.Upload.CreateChunkedUploader()
   at Controllers.TwitterControllers.TwTaskController.PostTweet(String code)

ExceptionMessage	ExceptionStackTrace
Object reference not set to an instance of an object at Tweetinvi.Upload.UploadImage(Byte[] binary)
   at Controllers.TwitterControllers.TwTaskController.PostTweet(String code)

ExceptionMessage	ExceptionStackTrace
Object reference not set to an instance of an object at Tweetinvi.Upload.UploadBinary(Byte[] binary)
   at Controllers.TwitterControllers.TwTaskController.PostTweet(String code)

Once it occurs, the fail rate increases significantly until I restart the application. (application pool)

**Comment by linvi** [comment] 2015-09-23 14:51
As mentioned few seconds ago, I have found the cause of this issue and will release a new version 0.9.9.7 tonight.

Linvi

**Comment by linvi** [comment] 2015-09-23 14:53
Before I do so I would be glad if you could both test the fix with your solution. I will provide the dll on this thread.

**Comment by Bastaspast** [comment] 2015-09-23 14:54
Nice one, will do.

**Comment by linvi** [comment] 2015-09-23 19:41
Guys would you please try the following DLL.

http://download-codeplex.sec.s-msft.com/Download?ProjectName=tweetinvi&DownloadId=1489523

Cheers,
Linvi

**Comment by Bastaspast** [comment] 2015-09-23 22:00
Implemented and testing as we speak. So far the issue is not reoccuring. A scheduled task will run all night (every 15 minutes) posting a tweet with image while i'm off to sleep. Tomorrow morning I'll report the results. Thanks for looking into this.

Kind regards,
Basta

**Comment by Bastaspast** [comment] 2015-09-24 06:06
No issues for 8 hours straight. Resolved imo.

**Comment by linvi** [comment] 2015-09-24 09:58
Tweetinvi 0.9.9.7 is available on nuget. It only includes the required fixes for this issue.

I wanted to thank you both for being prompt to reply, and take time to give feedback. I really appreciate it.

Cheers,
Linvi

**Closed by linvi** 2015-09-24 09:58 UTC
Labels: bug

**Comment by yangar** [comment] 2015-09-24 15:37
Look ok for me too, i m still doing some test and will report if any problem.
Thank you!!!

**Comment by jamesfmackenzie** [comment] 2016-04-12 07:14
There is a regression on this issue in the latest version (0.9.11.2). Reverting back to 0.9.9.7 fixed it for me.
