### ISSUE TITLE
Improper Redirect URL for the angular app.

### ISSUE THREAD

**Issue by saurabhabh** [linvi/tweetinvi#177] opened 2016-03-29 09:26 UTC
I am using the Tweetinvi dll with my angular app. I faced a problem while authorizing the user. 
I have given the redirect url as my angular route.

**http://localhost:2398/#/page/returnTwitterUrl**

so expect that i get something like this - 
**http://localhost:2398/#/page/returnTwitterUrl?authorization_id=38d79a10-c55f-44ef-a8ec-1aba3ab926d9&oauth_token=ZkbuCwAAAAAAt3hTAAABU8GR_rE&oauth_verifier=5UtILhiFfOxxuLpBUcvy8i1PrMAseBmY**

instead I get something like this -
**http://localhost:2398/?oauth_token=H-DgqgAAAAAAt3hTAAABU8FCRz8&oauth_verifier=eSapB8crXuRtylPe38eeQZ8OBPXCSiuN**_#/page/returnTwitterUrl_**?authorization_id=b7cbf25a-789b-4a37-aa95-07585348308f**

my return url gets scattered. Because of this I cannot get hold of the 'oauth_verifier' using the angular $location service. It returns only the 'authorization_id'.

**Note: ** Your MVC example is working fine.

**Comment by linvi** [comment] 2016-03-29 17:08
I have been able to reproduce the "problem".

I personally don't think this is a bug but an expected behaviour. The reason being that you would generally prefer to have the `consumer credentials` available to your server directly instead of passing them through your angular routing.

I have open a bug on Twitter [here](https://twittercommunity.com/t/request-token-with-redirect-url-containing-hashkey-and-query-parameters/64111). I would suggest that you follow it.

But as Tweetinvi is concerned there is no problem within the code.
Tweetinvi is sending your URL correctly and Twitter decides to return the URL with the credentials in the query parameter instead of the routing parameters.


In all the cases, you are redirected from Twitter to an "ASP.NET" page. If you want to pass the parameters through, I would suggest that you just use ASP.NET redirect to the URL you want, including your angular route parameters.

Does it makes sense?

PS: I will update the post as soon as I receive more news from Twitter.

**Comment by linvi** [comment] 2016-03-29 19:34
As you might have noticed in the Twitter thread, the behavior that you currently experience is the correct on (as per OAuth 1.0 specification).

If you really want to have the parameters sent to your route I would suggest that when you arrive to your auth router (in angular) you check the url of the current page. By checking the arguments available in the url, you will be able to detect that the url has query parameters and then redirect to the route that you want.

I am closing this issue as it is in fact by design.
If you need more advice feel free to ask :)

**Closed by linvi** 2016-03-29 19:34 UTC
Labels: bug
