### ISSUE TITLE
Authentication problems

### ISSUE THREAD

**Issue by juanjhb1894** [linvi/tweetinvi#864] opened 2019-05-24 15:53 UTC
I'm using the version 4.0.0 and using PIN-Based authentication  it use working like a moth before but now is not working anymore the code will be in this url: [http://pastiebin.com/embed/5ce813b0de0d4](url) the code works well, but the problem is that when I'm getting access the account with this code [http://pastiebin.com/embed/5ce81445de593](url) I'm receiving this error "System.NullReferenceException: 'Object reference not set to an instance of an object.'" I've also try using the Authentication from a specific set of credentials and the error continue appearing

**Comment by GodsWithin** [comment] 2019-05-24 16:51
Duplicate of https://github.com/linvi/tweetinvi/issues/850

**Comment by linvi** [comment] 2019-05-27 20:46
Please follow #850

**Closed by linvi** 2019-05-27 20:46 UTC
Labels: bug, duplicate
