### ISSUE TITLE
Unable to use Tweet.GetTweet to get a tweet using Application Only credentials in a UWP application

### ISSUE THREAD

**Issue by rymate1234** [linvi/tweetinvi#529] opened 2017-06-14 18:24 UTC
Hi, 

I'm using this library as a way of adding an inline tweet viewer in my UWP application, however my code to fetch a tweet no longer appears to work at least on my machines.

I've been using this code to reproduce the issue:

``` c#
try
{
	credentials = Auth.SetApplicationOnlyCredentials("", "", true);
	var rateLimits = RateLimit.GetCurrentCredentialsRateLimits();
	Console.WriteLine(credentials);
}
catch (Exception e)
{
	Console.WriteLine(e.Message);
	Console.WriteLine(e.StackTrace);
}

var tweet = Tweet.GetTweet(874866500083044353);

Console.WriteLine(tweet);

var latestException = ExceptionHandler.GetLastException();
Console.WriteLine("The following error occured : '{0}'", latestException.TwitterDescription);
```

When used in a .NET Core application, this code runs fine, however it fails to fetch the tweet when ran within a UWP Application

Any help is appreciated!

**Comment by linvi** [comment] 2017-06-14 23:11
Hello I am currently migrating Tweetinvi for PCL to .NETStandard 1.3.
If you have a problem this might solve it, so could you please wait few days as I expect to release this new version very soon.

**Comment by rymate1234** [comment] 2017-06-15 14:09
Alright, thanks for the information, will try that version once it's on nuget 👍

**Comment by linvi** [comment] 2017-06-15 19:58
Could you please provide the details of your UWP, .NET Version, Build Target, Build compatibility.

Ideally if you could send me a project that I can use to reproduce the problem it would make things easier to verify the new version solves your problem.

**Comment by rymate1234** [comment] 2017-06-16 16:46
Here's the project I tested it with.

Note, I am running the latest insider preview on my dev machine 

[TwitInviTest2.zip](https://github.com/linvi/tweetinvi/files/1080966/TwitInviTest2.zip)

**Comment by linvi** [comment] 2017-06-16 18:05
Have you tested with a SDK which is not in preview like :

> Windows 10 SDK v10.0.15063.400

**Comment by rymate1234** [comment] 2017-06-16 20:55
The project has the same issue when using the current Release SDK (15063) running on the insider preview (16215)

**Comment by linvi** [comment] 2017-06-18 20:04
Tweetinvi version 2.0 has now been added on nuget.
Could you please check it out and let me know if this worked for you.

**Comment by rymate1234** [comment] 2017-06-19 18:51
Yeah, I think this is a bug with the latest insider preview actually.

I tried it on my insider laptop and it still failed to work, however it works fine on my lumia running the latest release

**Comment by linvi** [comment] 2017-06-19 22:37
Thank you for checking it out. I am closing the bug for now. If you experience this bug when the preview becomes RTM please let me know.

**Comment by rymate1234** [comment] 2017-10-11 18:07
Hi, 

This issue is still happening on the final build of the fall creators update, build 16299, meaning it's a bug within Tweetinvi or something within the UWP version of .NET has changed to break TweetInvi

**Comment by linvi** [comment] 2017-10-11 22:40
Are you still using the same sample project?

**Comment by rymate1234** [comment] 2017-10-12 07:31
Yeah, I tried the sample project using the 16299 SDK and it failed to fetch a tweet on build 16299, with the following error:

> Bad Request - The request was invalid or cannot be otherwise served. An accompanying error message will explain further. In API v1.1, requests without authentication are considered invalid and will yield this response.

It successfully fetches a tweet when ran on my tablet running the anniversary update.

I'm using application only credentials to fetch tweets.

**Comment by rymate1234** [comment] 2017-11-04 19:45
Hi, not sure if you're aware of this, but the issue still occurs on the 2.1 update you released

**Comment by linvi** [comment] 2018-03-24 19:58
Hello,

After various investigation I am still unable to reproduce this issue.
If you can share your project or a sample where you can reproduce the issue I will have a look at it but at the moment there is nothing I can do about it.

Please let me know if you can share a project where the bug is reproducible.

Thanks,
Linvi

**Comment by linvi** [comment] 2018-03-24 20:07
Sorry, 

I wanted to mention that I tried your project but it works properly on my machine.

Let me know if you have any news regarding this issue.

Thanks,
Linvi

**Comment by linvi** [comment] 2018-03-24 20:13
Unfortunately I am closing it again. Please get back to me if you have more info.

Sorry about that.

**Closed** 2018-03-24 20:13 UTC
Labels: bug, question
