### ISSUE TITLE
PublishTweetWithImage not working

### ISSUE THREAD

**Issue by Asshen** [linvi/tweetinvi#450] opened 2017-01-30 16:19 UTC
Tweet.PublishTweetWithImage is not working for me.
I receive no errors, it just doesn't post to Twitter.

Tweetinvi version = 1.2.0.1 (nuget package)

I'm using it in an asp.net MVC application as follows:
```
byte[] imageBytes = webClient.DownloadData( imageUrl );
Tweet.PublishTweetWithImage( text, imageBytes );
```

The image is fine, example: http://s123.eu/uploads/media/1/b9272763d8e640b1ba16.jpg
I receive the byte data, no issues there.
Tweetinvi just doesn't seem to post it on Twitter.

I also use Tweet.PublishTweet for tweets without image and that is working fine.

I also tried this alternative, but it is also not working:
```
var media = Tweetinvi.Upload.UploadImage( imageBytes );
Tweet.PublishTweet( text, new PublishTweetOptionalParameters { Medias = { media } } );
```
     
Any suggestions?
Thanks.
 @Asshen

**Comment by Unkindjolt** [comment] 2017-02-01 15:11
how are you initiating the process? Button click event or Thread?

**Comment by Unkindjolt** [comment] 2017-02-02 07:51
It looks like your if (data == null) is missing { } um also maybe try
adding Auth.SetUserCredentials
("consumer","consumer_secret","access_token","access_token_secret") within
the try statement or just above tweet.publish

On 2 Feb 2017 6:42 pm, "Asshen" <notifications@github.com> wrote:

I post some data (text and image) to an MVC controller, and then execute
the above code.
Here is the controller, there are 2 methods of posting a tweet with media
(second is commented out), none of them work.

        [HttpPost]
        public bool Post( [FromBody]TwitterPostData data )
        {
            try
            {
                if( data == null )
                    return false;

                string text = data.text; // text to post
                string image = data.image; // url of the image

		byte[] imageBytes = webClient.DownloadData( image );

		Tweet.PublishTweetWithImage( text, imageBytes );

		// var media = Tweetinvi.Upload.UploadImage( imageBytes );
                // Tweet.PublishTweet( text, new
PublishTweetOptionalParameters { Medias = new List<IMedia> { media } }
);

                return true;
            }
            catch(Exception ex)
            {
                Logging.Append( ex );
            }

            return false;
        }
    }

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/linvi/tweetinvi/issues/450#issuecomment-276888773>, or mute
the thread

**Comment by Unkindjolt** [comment] 2017-02-02 07:51
Again I'm used to C# so im not 100% on the if statement

**Comment by Asshen** [comment] 2017-02-02 07:54
{ } around the if statement? That's definitely not the problem.

I don't think I need to add the usercredentials, because Tweet.PublishTweet( text ) without the media works without problems.

**Comment by Unkindjolt** [comment] 2017-02-02 07:59
From documentation ive seen that the tweet with media takes a file instead
of a byte array, and i know its not the same language but arent if
statements

if (foo==bar){
//insert alg here
}

**Comment by Unkindjolt** [comment] 2017-02-02 08:00
Or for vb
if foo = bar then

EndIf

**Comment by Asshen** [comment] 2017-02-02 08:01
Let's not argue about those parenthesis, I've been a C# developer for more than 15 years :-)
Those are not the problem.

See here for the documentation, that's exactly what I'm doing: https://github.com/linvi/tweetinvi/wiki/Tweets#publish-a-tweet-with-media

**Comment by Unkindjolt** [comment] 2017-02-02 08:11
Ill try replicating it shortly

**Comment by Unkindjolt** [comment] 2017-02-02 08:43
I'm going to be Replicating in C#, if it works I'll send you what I got.
I'm sure you'll be able to convert it to the language you are using. Given
your experience. :)

**Comment by Asshen** [comment] 2017-02-02 08:44
Thank you for your help.

**Comment by Unkindjolt** [comment] 2017-02-02 08:44
No problem :)

**Comment by Unkindjolt** [comment] 2017-02-02 09:03
Are you trying to get the image from a tweet, to then tweet using the
account that is authorised? " public bool Post( [FromBody]TwitterPostData
data ) " " string image = data.image; "

**Comment by Unkindjolt** [comment] 2017-02-02 09:04
Also how are you authenticating the user? is it PIN or using the
C,CS,AT,ATS manaully?

**Comment by Unkindjolt** [comment] 2017-02-02 09:04
*manually

**Comment by Unkindjolt** [comment] 2017-02-02 09:07
Just tested just the tweetwithmedia model, public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET",
"ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var webClient = new WebClient();
            byte[] imageBytes = webClient.DownloadData("
http://unkindbrotherhood.com/favicon.png");
            Tweet.PublishTweetWithImage("Testing Tweet With Media",
imageBytes);

        }
    }
I replaced my keys and tokens with CONSUMER_KEY etc. just so that my keys
aren't available on email/github here

**Comment by Asshen** [comment] 2017-02-02 09:08
And that worked?

**Comment by Unkindjolt** [comment] 2017-02-02 09:09
yeah that worked

**Comment by Asshen** [comment] 2017-02-02 09:12
Weird. In any case it doesn't work in my controller ;)
But since your version works, I will need to debug a little more to find what's stopping it from working in my case...

**Comment by Unkindjolt** [comment] 2017-02-02 09:13
that's fair enough could there be an error with getting the Image data from "data" ? is there away you could get a response code?

**Comment by Asshen** [comment] 2017-02-02 09:15
As stated in my original post (on top of this page), I get the image data without any problem.
I can also post a text to Twitter without any problem.
Only when I try to add the image to the post, then it doesn't work.

**Comment by Unkindjolt** [comment] 2017-02-02 09:16
Ah I thought, you could only get the text, was a bit confused there.

**Comment by Unkindjolt** [comment] 2017-02-02 09:23
This also works,
```
 var media = Tweetinvi.Upload.UploadImage(imageBytes);
            Tweet.PublishTweet("Testing Tweet With Image 2", new PublishTweetOptionalParameters { Medias = { media } });
```

```
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET",
"ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var webClient = new WebClient();
            byte[] imageBytes = webClient.DownloadData("
http://unkindbrotherhood.com/favicon.png");
            var media = Tweetinvi.Upload.UploadImage(imageBytes);
            Tweet.PublishTweet("Testing Tweet With Image 2", new PublishTweetOptionalParameters { Medias = { media } });

        }
    }
```

**Comment by Asshen** [comment] 2017-02-02 09:24
Thank you for all your help.
Looks like I will need to find the problem in my environment.
No need to waste any more of your time on this ;-)

**Comment by Unkindjolt** [comment] 2017-02-02 09:25
Ok, no problem :) have a good day/night :)

**Comment by linvi** [comment] 2017-02-06 00:50
Hello there.

First of all thank you @Unkindjolt for taking a look and trying to help here.

@Asshen in order to help you would you please deactivate the global exception handler and return to me the exception that Tweetinvi throws.

You can learn more about ExceptionHandling here : https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling

**Comment by Asshen** [comment] 2017-02-06 07:56
There is no exception.
Everything executes without error, but the post (with media) is not posted on Twitter.

**Comment by Asshen** [comment] 2017-02-06 15:18
Okay, sorry about the above, I didn't read your link good enough.
I get the following error:

```
https://api.twitter.com/1.1/statuses/update.json?status=All%20hail%20the%20maze%20of%20galious%0Ahttps%3A%2F%2Fs123.eu%2Fms%2Fd9fea076679640208e71%0Ahttps%3A%2F%2Fs123.eu%2FUploads%2FMedia%2F1%2F32c91e1ef7454ca3b3a0.png&media_ids=0 web request failed.
False
   at Tweetinvi.Credentials.TwitterAccessor.HandleQueryException(TwitterException ex)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
   at Tweetinvi.Credentials.TwitterAccessor.ExecutePOSTQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Tweet.TweetQueryExecutor.PublishTweet(IPublishTweetParameters publishParameters)
   at Tweetinvi.Controllers.Tweet.TweetController.InternalPublishTweet(IPublishTweetParameters parameters)
   at Tweetinvi.Controllers.Tweet.TweetController.PublishTweet(String text, IPublishTweetOptionalParameters optionalParameters)
   at SocialShare.Models.TwitterAuthentication.TwitterPost(String text, String image, Int32 userFK) in E:\_projecten\FBD-Social-Share\SocialShare\SocialShare\Models\TwitterAuthentication.cs:line 198
```

**Comment by IsaaacD** [comment] 2017-03-30 17:41
I'm also experiencing the same issue, I've even ran the Example.Web project and used the Tweet/Index view to attempt with your example and it fails as well. Did twitter change their media upload api recently?
![image](https://cloud.githubusercontent.com/assets/5303125/24518085/9b4b0112-154e-11e7-98a4-a4d91b6a1e27.png)

**Comment by IsaaacD** [comment] 2017-03-30 18:10
As a follow up, I've debugged the source code and I've identified where the issue resides. I'll include a bit of the call stack from the code if you want it, but TwitterRequestHandler.TryPrepareRequest passes null credentials and so the creds are grabbed from _credentialsAccessor.CurrentThreadCredentials which does not have valid key or secret. When I replaced them with the appropriate values while debugging it works flawlessly, so it's something to do with the _credentialsAccessor.CurrentThreadCredentials... My guess is that since@Unkindjolt was using forms instead of mvc/web api that there was no threading issue and it likely comes from there... I'll keep investigating

**Comment by IsaaacD** [comment] 2017-03-30 19:36
I was able to get this to work successfully with the following code:

            var imageUrl = "http://i.imgur.com/DoDiXTx.jpg";
            var tweetMsg = "testing";
            var request = (HttpWebRequest)WebRequest.Create(imageUrl);
            request.Timeout = 10000;

            byte[] imgBytes = null;

            var response = request.GetResponse();

            if (request.HaveResponse)
                using (var stream = response.GetResponseStream())
                {
                    if (stream != null)
                    {
                        using (var memStream = new MemoryStream())
                        {
                            stream.CopyTo(memStream);
                            imgBytes = memStream.ToArray();
                        }
                    }
                }

            var publishedTweet = Tweetinvi.Auth.ExecuteOperationWithCredentials(userCreds, () =>
            {
                var publishOptions = new PublishTweetOptionalParameters();
                if (imgBytes != null)
                {
                    publishOptions.MediaBinaries.Add(imgBytes);
                }
                
                return Tweet.PublishTweet(tweetMsg, publishOptions);
            });

**Comment by Asshen** [comment] 2017-04-04 07:36
Thank you for the tip IsaaacD!
I will try it out asap.

Kind regards.
K.

**Comment by linvi** [comment] 2017-05-04 13:25
@Asshen was the problem about your credentials not being properly initialized?

Can I close this issue?

**Comment by Asshen** [comment] 2017-05-04 14:15
Hey.

It seems to me this is a bug, no?
So why would you close it? Is the bug fixed?

K.

**Comment by linvi** [comment] 2017-05-04 23:17
Well I am not sure if it is a bug. I think the problem comes from the fact that the credentials are not initialized.

Have you tried to use `Auth.SetUserCredentials` at the begining of the Post method?
Have you tried using the code that @IsaaacD provided?

**Comment by Asshen** [comment] 2017-05-05 06:20
Hey.

Sadly I didn’t find the time yet, it has been busy here at work.

You know what, just close the issue, I can always reopen it I guess?

Kind regards.
Kris

**Comment by linvi** [comment] 2017-05-05 07:55
No, no. Just take the time you need to share a sample project to reproduce the issue and I will work with you on it.

**Closed** 2017-10-02 23:01 UTC
Labels: question
