### ISSUE TITLE
SearchTweets: OR does not seem to be honored

### ISSUE THREAD

**Issue by CedricMi** [linvi/tweetinvi#213] opened 2016-05-02 21:35 UTC
This should work according to the Twitter Documentation and the Twitter advanced search query builder, but it doesn't:
var tweets = Search.SearchTweets("@Apple OR @Microsoft");   // [See the expected and working search](https://twitter.com/search?q=%40Apple%20OR%20%40Microsoft&src=typd)
seems somehow to be interpreted as @Apple @Microsoft (@Apple AND @Microsoft)
Ditto for 
"@Apple OR @Microsoft OR #Google": [See the expected and working search](https://twitter.com/search?q=%40Apple%20OR%20%40Microsoft%20OR%20%23Google&src=typd)
OR are intepreted as AND.

Same for the search with search parameters, e.g.
var tweets = Search.SearchTweets(searchParameter);

**Comment by linvi** [comment] 2016-05-03 09:42
I will investigate this issue.

**Comment by CedricMi** [comment] 2016-05-03 09:58
Thanks.
In the meantime I simple do 3 searches and assemble them.

I have another question.
I have received a tweet with '&amp;' which is the HTML character code for '&'.
if Twitter encodes responses in UTF8, shouldn't I get an '&' instead of an '&amp;' ?

**Comment by linvi** [comment] 2016-05-03 10:19
Could you share the ID of the tweet you are referring to?

**Comment by CedricMi** [comment] 2016-05-03 10:25
[Here it is](https://twitter.com/RenoultJonathan/status/727319192802828288)

**Comment by linvi** [comment] 2016-05-03 10:26
Thanks I will take a look tonight. Also I should have all I need for the Raspberry Pi tonight.

**Comment by JoshKeegan** [comment] 2016-05-20 13:35
About the HTML chars:
I assumed this was the intended behaviour from Twitter as the indices returned are correct for &amp; and other HTML encoded chars.
To decode the HTML escaped chars & correct indices I wrote https://github.com/JoshKeegan/HtmlEncoder

I think this is beyond the scope of Tweetinvi though, or if something like this were to be included then it should be an option as I expect most people will be displaying tweets as HTML anyway.

**Comment by linvi** [comment] 2016-05-22 15:57
I am closing this issue because :

* **OR** operator properly works. If it did not at some point it was not due to Tweetinvi, but only the fact that Twitter was no longer returning the incorrect data. It seems to work properly now.
* Second problem has been answered by @JoshKeegan .

Thanks @JoshKeegan. I will take a look and consider your library (I am creating a new work item in tweetinvi version 1.3).

**Closed by linvi** 2016-05-22 15:57 UTC
