### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by anjana-sharma** [linvi/tweetinvi#714] opened 2018-05-31 05:48 UTC
Tweetinvi is throwing exception on Rate Limit tracking and application stopped working

**Comment by chriswill** [comment] 2018-05-31 05:50
Duplicate of #713

**Comment by linvi** [comment] 2018-05-31 07:08
Closing as it is will be taken care of as part of the #713.

**Closed by linvi** 2018-05-31 07:08 UTC
Labels: duplicate
