### ISSUE TITLE
Modified DLL Tweetinivi.Logic also throwing error

### ISSUE THREAD

**Issue by DavidBusayo** [linvi/tweetinvi#867] opened 2019-05-27 05:57 UTC
![image](https://user-images.githubusercontent.com/51048612/58398329-2f4f6100-806e-11e9-9c20-72bf7e69f13a.png)

**Comment by GodsWithin** [comment] 2019-05-27 16:34
Looks like it's just missing a reference to the System.Reflection.TypeExtensions assembly?
Should be available through entering `Install-Package System.Reflection.TypeExtensions -Version 4.5.1` in the NuGet console.

**Comment by linvi** [comment] 2019-05-27 22:17
Please install the latest version of Tweetinvi 4.0.1.

``` sh
Install-Package TweetinviAPI -Version 4.0.1
```

**Comment by linvi** [comment] 2019-05-27 22:17
Duplicate of #850

**Closed** 2019-05-27 22:19 UTC
Labels: bug, duplicate
