### ISSUE TITLE
Cant seem to AND users with Ored tracks

### ISSUE THREAD

**Issue by HarryMcCarney** [linvi/tweetinvi#518] opened 2017-05-31 20:51 UTC
Thanks for the great library

I want capture tweets from a set of accounts that mention any of the following key phrases. 

So my code looks like 

 ``` c#
 var stream = Tweetinvi.Stream.CreateFilteredStream();
            stream.AddTrack("Liverpool");
            stream.AddTrack("Help");
            stream.AddTrack("Elenaor");

 foreach (var a in Accounts)
            {
                var user = User.GetUserFromId(a.Id); // where accounts are fans
                stream.AddFollow(user);
            }

stream.MatchingTweetReceived += (sender, args2) =>
            {
                Console.WriteLine(args2.Tweet.CreatedBy.ScreenName);
                    Console.WriteLine(args2.Tweet.Text);
              
                }
stream.StartStreamMatchingAllConditions();
```

Unfortunately, it looks as though StartStreamMatchingAllConditions requires all the keywords to be present in a tweet from the target accounts.
Whilst stream.StartStreamMatchingAnyConditions(); seems to let through tweet which match a keyword but which are not from my target accounts.

Grateful for any pointers, or if the library can't currently do this I will try to create a pull request.

**Comment by linvi** [comment] 2017-06-12 13:20
It looks like a bug. This will be investigated.

**Comment by linvi** [comment] 2017-10-06 18:31
I have tested this out and I could not reproduce the bug nor can I find any logic going wrong with the code.

Could you let me know which version of Tweetinvi you are using please?

**Comment by linvi** [comment] 2017-10-07 10:53
Closing for now as I don't think there is a bug out there. Feel free to reopen.

**Closed by linvi** 2017-10-07 10:53 UTC
Labels: bug
