### ISSUE TITLE
Could not authenticate issue

### ISSUE THREAD

**Issue by masfoobar** [linvi/tweetinvi#483] opened 2017-04-05 09:13 UTC
I originally uploaded this on twittercommunity (yesterday) and one the twitter staff claims it is likely an encoding issue. So, I have copied the main parts of the original message relevent here (removing some fluff not directed to tweetinvi.)

for the sake of history/context - this is the topic I posted - https://twittercommunity.com/t/could-not-authenticate-you/84375

---- below ----

Hi

I have Twitter API setup for a local application in C# (using Tweetinvi). Everything is in place and working.

However -
for a small amount of messages per week, I get a response of Code 32 - "could not authenticate you" - I have not changed the credentials or anything as follow up messages that enter the queue go through just fine. When I try and re-send the one in question it comes back with the same response.

Because we need these messages added to our Twitter channel, we end up logging in directly to the site and pasting the message/tweet. This works fine. Why does it not work through the API/Tweetinvi?

I have tried removing some characters in the original message and re-sending it hoping to find some clue of where the problems is. Sometimes the message still comes back with the same response. Other times, after removing a certain character(s) - it eventually is sent successfully.

For example, in one message, removing the '£' characters solved the problem. For another, it was removing a '[' near the end of the message. For another, it was removing the '[2 of 2]' at the beginning of the message. These are completely random.

 All messages are under 140 characters (I believe the 'Status over 140 characters' response would be returned if the case, before the problem explained above, anyway)

I hope I have explained my problem.

Here is an example tweet (without the double-quotes) -
"[3 of 3] concessions £37 SW99 9XX"

When the error is returned (using breakpoints in Visual Studio) -  This is the url of the message
https://api.twitter.com/1.1/statuses/update.json?status=[3%20of%203]%20concessions%20%C2%A337%20SW99%209XX

It would be good to hear from others on this subject - and if a tweet above (using tweetinvi) worked fine for them.

**Comment by masfoobar** [comment] 2017-04-05 11:29
With regards to the tweet example above -
"[3 of 3] concessions £37 SW99 9XX"

It works if I do
""

OR

""

**Comment by masfoobar** [comment] 2017-04-05 11:36
I have just tested another (longer) message that fails, and sent one without the '£' and another without the squared brackets characters. The same method I applied to the previous comment. They both were sent successfully.

So, it appears to link with messages that have both a '£' and '[' and/or ']' characters in them.

**Comment by masfoobar** [comment] 2017-04-05 12:04
I have replaced squared brackets with round brackets - and now these messages appear to be working just fine... even those with '£'

So I am not quite sure what the problem is.

**Comment by JoshKeegan** [comment] 2017-04-21 11:13
Reproduced. Fails with something as simple as:
test [ £

Not just for the pound sign though, also tried:
test [ ‎¥

and that failed too.

Needs debugging. I wouldn't like to call whether this is a Tweetinvi or Twitter bug though :)

**Comment by JoshKeegan** [comment] 2017-05-05 14:51
This is now working for me!
So perhaps it was a Twitter bug & they've now fixed it?

I only tested this again because I got the error when sending another tweet though, so if you found anything more out about this I'd love to know!

**Comment by JoshKeegan** [comment] 2017-05-05 15:33
OK, so my new error was caused by a bug in my code for #497 (comma not being URL encoded) - have added a commit to that same PR to fix it, so that had nothing to do with this issue.

I have also now tried posting "test [ ‎¥" from my production system (still using the version of Tweetinvi I previously tested with) and still get the "Could not authenticate you." error so it looks like it **is/was** a Tweetinvi bug, but has already been fixed somewhere between e85aea0aab0d6757b880c2228e324d06b6285ce9 and the latest code I'm using.

**Comment by linvi** [comment] 2017-09-29 18:14
All tested and working in 2.1.

**Closed by linvi** 2017-09-29 18:14 UTC
Labels: bug
