### ISSUE TITLE
System.TypeInitializationException in system.net.http.primitives

### ISSUE THREAD

**Issue by sumowesley** [linvi/tweetinvi#95] opened 2015-12-12 16:56 UTC
I've installed Tweetinvi via Nuget but get the following message when I try to set the credentials for my twitter session.

System.TypeInitializationException: The type initializer for 'Tweetinvi.Auth' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Tweetinvi.WebLogic.TweetinviWebLogicModule.Initialize()
   at Tweetinvi.Injectinvi.AutofacContainer.InitializeModules()
   at Tweetinvi.Injectinvi.AutofacContainer.Initialize()
   at Tweetinvi.TweetinviContainer.Resolve[T]()
   at Tweetinvi.Auth.Initialize()
   at Tweetinvi.Auth..cctor()
   --- End of inner exception stack trace ---

There is a System.Net.Http.Primitives file in my binaries with version 4.2.29.0

Is there a dependency on something else?

**Comment by sumowesley** [comment] 2015-12-14 10:36
Think I found the reason but not sure of an immediate workaround. Portable Class library for system.net.http.primitives is stuck at 1.5.0.0 so hard to reference tweetinvi other than in a portable project.

Not sure there is a problem - my misunderstanding was the root cause.

**Comment by greglindquist** [comment] 2016-04-18 20:04
Just curious, what was the root cause for your issue on this? I'm running into something similar and am  still tracking it down for me.

**Comment by sumowesley** [comment] 2016-04-18 21:20
i couldn't get it to work in the versions I had I'm afraid. I hadn't appreciated it was a portable class - it wasn't of use to me.

**Comment by greglindquist** [comment] 2016-04-18 21:23
I appreciate your feedback. I eventually was able to resolve my issue and found it related to my application config and had somehow gotten the version number to something my system didn't have. I did also update my machine.config, although I'm not sure if that was necessary or not.

**Comment by linvi** [comment] 2016-04-18 21:39
Portable Class or not, the library should work for every project targeting .NET Framework 4.0 and later.

If you are experiencing a problem with Tweetinvi, please let me know the version of Tweetinvi you are trying to use, the .NET Framework you are targeting and the type of project you are working on (Console, WPF, ASP.NET, iOS, Android, Rasbery Pi...).

PS : If you attempted to install Tweetinvi 0.9.12.0 with a .NET Framework 4.0, the merged binaries on nuget did not work properly. Please upgrade to 0.9.12.1.

**Comment by linvi** [comment] 2016-04-18 21:41
@greglindquist

Please share the problem you encountered and the solution you found. This will help other people in the future.

**Comment by greglindquist** [comment] 2016-04-18 21:50
@linvi  What I experienced wasn't an issue with the code, really. From what I can tell, someone on our dev team targeted the wrong version of the "system.net.http.primatives" namespace to a version that did not exist on my machine and was throwing an error during runtime as a result of it. Once I targeted to a valid dll, the issue resolved itself.

**Comment by Zaharah** [comment] 2017-10-09 15:13
Hi, I also having the System.TypeInitilizationException in my code. The inner exception says "{"Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}". 

I can't figure it out. I have tried to update the System.Net.Http dll as well as Newtinsoft.json. Any help would be greatly appreciated. I working with a simple console app. The exception appears at Auth.SetUserCredentials(...).

**Comment by linvi** [comment] 2017-10-09 18:31
@Zaharah Please read the following : https://github.com/linvi/tweetinvi/releases/tag/2.0

Section : ASP.NET (.NET Framework) considerations

**Comment by Zaharah** [comment] 2017-10-09 19:25
@linvi Thanks for the link. I managed to fix it. I had to change the .Net framework to 4.6.

**Comment by linvi** [comment] 2017-10-09 20:05
@Zaharah For the record and helping future developers encountering the same issue. Could you let me know which type of project you were trying to create.

- Console
- ASP.NET
- ASP.NET Core
- WPF
- W10 UAP
- ...

Thank you

**Comment by Zaharah** [comment] 2017-10-10 07:54
I am working on Windows Forms Application.

**Comment by dylsmith8** [comment] 2017-10-14 12:42
Hi, also having a similar issue to @Zaharah with System.net.http. My simple console app is targeting .NET 4.6 and have included the necessary assembly dependencies in my app.config as mentioned in https://github.com/linvi/tweetinvi/releases/tag/2.0

**Comment by linvi** [comment] 2017-10-14 12:47
Hello @dylsmith8 

Could you share your project please?

Cheers,
Linvi

**Comment by dylsmith8** [comment] 2017-10-14 16:44
@linvi Thanks for the reply :) So I tried creating a new WinForms app that targets .NET 4.6 and reinstalled tweetinvi. The assembly dependencies in app.config `System.Runtime.Serialization.Primitives` and `System.Net.Http` were automatically created. Getting a different error now: upon build, complains that there are "multiple assemblies with equivalent identities have been imported". If I remove the reference in the Solution Explorer, it builds but an exception is thrown stating "could not load file or assembly System.Runtime.Serialization.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies".....

Not sure if I am doing something stupid or legitimate issue? Just stumbled across this library the other day and in process of trying it out. Attached is the test project. Thanks for the help
[WindowsFormsApplication1.zip](https://github.com/linvi/tweetinvi/files/1384802/WindowsFormsApplication1.zip)

**Comment by linvi** [comment] 2017-10-14 17:57
@dylsmith8 thank you for sharing the project and describing how you encounter it.

I will test this code/bug tomorrow as I won't have time tonight.
I will let you know how things go.

Cheers,
Linvi

**Comment by linvi** [comment] 2017-10-21 18:46
@dylsmith8 I have been able to reproduce your issue. I am currently working on it.

The fix will be available for the next release.

**Comment by linvi** [comment] 2017-10-21 23:58
Some further improvements will be provided : 

- WPF + Winform Sample projects for testing library as it seems that default dependencies are different for this types of projects.

**Comment by dylsmith8** [comment] 2017-10-22 10:02
@linvi thanks for the update :)

**Closed** 2017-10-25 23:04 UTC
Labels: question
